modLoader = "kotlinforforge"
loaderVersion = "[6.2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "noitemloss"
version = "${version}"
displayName = "NoItemLoss"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.noitemloss]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.35-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.noitemloss]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.noitemloss]]
modId = "architectury"
type = "required"
versionRange = "[21.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "noitemloss.mixins.json"
